// <auto-generated/>
using System;
using System.Web.UI;

namespace Tatooine
{
    public partial class Contact : Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            if (Session["UserName"] != null && Session["Pwd"] != null)
            {

            }

            Response.Redirect("Login1.aspx");
        }
    }
}