// <auto-generated/>
using System;
using System.Web.UI;
namespace Tatooine
{
    public partial class _Index : Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!Page.IsPostBack)
            {
                GreetingsLabel.Text = "Bienvenido a Tatooine";
            }
        }
    }
}