// <auto-generated/>
using BE;
using System;
using System.Web.UI;

namespace Tatooine
{
    public partial class SiteMaster : MasterPage
    {
        public User user { get; set; }

        protected void Page_Load(object sender, EventArgs e)
        {
            if (Session["user"] != null)
            {
                user = (BE.User)Session["user"];
            }
        }

        public bool isAdmin(User user)
        {
            foreach (var family in user.Families)
            {
                if (family.Description == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }

            return false;
        }

    }
}